# Project
site_url: https://www.56yhz.com
site_name: GreaterWMS Documentation
site_description: GreaterWMS - Open Source Inventory Management
site_author: GreaterWMS

repo_name: GreaterWMS
repo_url: https://github.com/GreaterWMS/GreaterWMS

copyright: Copyright &copy; 2016 - 2023 GreaterWMS Team

theme:
  name: material
  custom_dir: material/.overrides
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  edit_uri: "" # Disable "Edit" button

extra:
  annotate:
    json: [.s2]
  generator: false
  analytics:
    provider: google
    property: G-1TRGFWFWSZ
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GreaterWMS/GreaterWMS
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/greaterwms/greaterwms_backend
    - icon: fontawesome/brands/python
      link: https://www.python.org/
    - icon: fontawesome/brands/vuejs
      link: https://vuejs.org/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCPW1wciGMIEh7CYOdLnsloA
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/407321291/channel/seriesdetail?sid=776320

plugins:
  - search:
      lang:
        - en
        - zh
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
  - glightbox
  - i18n:
      default_language: en
      material_alternate: true
      languages:
        en:
          name: English
          build: true
        zh:
          name: 中文简体
          build: true
      nav_translations:
        zh:
          Home: 主页
          Guide: 指南
          Why GreaterWMS: 为什么选择我们
          Sponsors and Supporters: 赞助商和支持者
          Why Donate?: 为什么捐助很重要
          Please Don't Do That: 不要做这些
          Deploy: 部署文档
          Software Version Requirements: 软件版本要求
          Server Configuration Recommendations: 服务器要求
          Win10 X64: Win10 X64
          Centos 7 64-bit Deployment: Centos 7 部署
          Ubuntu20 X64: Ubuntu 20 部署
          Android Environment: 安卓环境搭建
          IOS Environment: IOS环境搭建
          Android Apk Signature: 安卓APK签名
          Supervisor Process Guarded: Supervisor守护进程
          Nginx Config: Nginx反向代理
          Electron APP: Electron构建
          Executive Summary: 命令集合
          Docker deployment: Docker部署
          Product: 产品线
          GreaterWMS: GreaterWMS
          DVadmin: DVadmin
          WCS: WCS
          Case: 成功案例
          Contact: 联系我们
          Contact US: 联系方式

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Guide:
    - Why GreaterWMS: why_greaterwms.md
    - Sponsors and Supporters: sponsors_and_supporters.md
    - Why Donate?: why_donate.md
    - Please Don't Do That: please_dont_do_that.md
  - Deploy:
    - Software Version Requirements: software_version_requirements.md
    - Server Configuration Recommendations: server_configuration_recommendations.md
    - Win10 X64: win_10.md
    - Centos 7 64-bit Deployment: centos_7.md
    - Ubuntu20 X64: ubuntu_20.md
    - Android Environment: android_environment.md
    - IOS Environment: ios_environment.md
    - Android Apk Signature: android_apk_signature.md
    - Supervisor Process Guarded: supervisor_process_guarded.md
    - Nginx Config: nginx_config.md
    - Electron APP: electron_app.md
    - Executive Summary: executive_summary.md
    - Docker deployment: docker_deployment.md
  - Product:
    - GreaterWMS: greaterwms.md
    - DVadmin: dvadmin.md
    - WCS: wcs.md
  - Case: show_case.md
  - Contact:
    - Contact US: contact_us.md

